# Review of Statistical Inference {#review}

## Sampling Distribution
Suppose we take a random sample of size $n$ from a large population of individuals. We record a variable and compute a **statistic** like a sample mean or sample proportion from this data. The **sampling distribution** of the statistic describes how the stat is distributed over many random samples:

1. take a random sample of size $n$
2. record the variable of interest (data) for the $n$ sampled cases
3. compute the statistic from the data
4. repeat 1-3 many, many times
5. plot the distribution of your statistics from step 4.

## Central Limit Theorem
Under the right conditions, the distribution of many sample means $\bar{x}$ or proportions  $\hat{p}$ will look like a normal distribution that is centered at the true population parameter (mean $\mu$ or proportion $p$) value. 

- Shape: normally distributed ("bell-shaped")
- Center: true population parameter value
- Variation: called the **standard error** of the statistic which measures the standard deviation of your statistic over many samples

The conditions for "normality" (symmetry) have to do with both the sample sized and the distribution of your variable.

- If your measurements are very symmetric (e.g. heights of woman in an adult population) then the sample size $n$ can be very small and the sample mean will behave normally.
- As your measurements get more skewed (e.g. income per person in a large city), then the sample size $n$ needs to get larger for the sample mean to behave normally.
- Outliers are always a problem, even if you have a large sample size, since means can be easily influenced by one or two very unusual cases. 

### Standard error
The standard error of the sample mean $\bar{x}$ measures the variability of this statistic and is the standard deviation of the sampling distribution for $\bar{x}$. Roughly, the SE of any statistic tells us how it will vary from sample to sample. 

For the sample mean statistic, the **estimated SE** is equal to 
$$
SE(\bar{x}) = \dfrac{s}{\sqrt{n}}
$$
where $s$ is the **sample standard deviation** of your variable. For the **difference of two sample means**, $\bar{x}_1 - \bar{x}_2$, the standard error is
$$
SE(\bar{x}_1 - \bar{x}_2) = \sqrt{\dfrac{s^2_1}{n_1} + \dfrac{s^2_2}{n_2}}
$$
where $n_i$ is the sample size of sample $i$ and $s_i$ is the sample SD of population $i$. 

For the sample proportion $\hat{p}$, the standard error is 
$$
SE(\hat{p}) = \sqrt{\dfrac{p(1-p)}{n}}
$$
where $p$ is the true population proportion. To **estimate** this SE we just use the sample proportion $\hat{p}$ in the SE formula. 

## Hypothesis testing
Your null hypothesis $H_0$ is a specific claim about a **population parameter** of interest. Examples include:

- $H_0: p = 0.5$ (population proportion is 0.50, or 50%)
- $H_0: \mu_1 - \mu_2 = 0$ (the mean of population 1 $\mu_1$ is equal to the mean of population 2 $\mu_2$)

The alternative hypothesis specifies another, more general, scenario for the population(s). Examples include:

- $H_0: p > 0.5$ (population proportion greater than 0.50)
- $H_0: \mu_1 - \mu_2 \neq 0$ (the two populations have difference means)

You then use a **test statistic** to measure how far the data (e.g. sample statistic) deviates from what is expected **assuming the null is true**. Often these test stats take form of a standardized values so large absolute values indicate data that deviates a lot from what is expected if the null is true. 

For a hypothesis about one population mean $H_0: \mu = \mu_0$, we use a **t-test statistic**:
$$
t = \dfrac{\bar{x} - \mu_0}{s/\sqrt{n}}
$$
To test for a **difference in two means**, we use another t-test stat:
$$
t = \dfrac{(\bar{x}_1 - \bar{x}_2) - 0}{\sqrt{\dfrac{s^2_1}{n_1} + \dfrac{s^2_2}{n_2}}}
$$


We then construct the sampling distribution of the test statistic under the assumption that **the null hypothesis is true**. Using this model, we compute a **p-value** by finding the probability of getting a test stat as, or more, extreme as the observed test stat. The p-value measures the probability of observing data as unusual, or more usual, than the observed data if the null is true. Small p-values indicate data that would rarely be seen if the null is true which means we have evidence (data) that supports the alternative hypothesis. 

## Confidence Intervals

The sampling distribution is used to construct the correct margin of error for any level of "confidence". The usual CI form is  estimate $\pm$ margin of error. The margin of error is computed so that, say, 95% of the time the estimate will be within the "margin of error" of the truth. A rough guess at a 95% margin of error is $2\times SE$. 

